<?php
if($okay_to_be_here !== true)
  exit();
?>
<div class="booktext">
<p><center><span class="size16"><strong>The History of Atlantis</strong></span><br />
<span class="size12"><i>as retold by Critias</i></span></center></p>
<p>There is in Egypt, in the Delta, at the head of which the river Nile divides, a province called Sais, and the chief city of this province is also Sais, the birthplace of Amasis, the king.  The founder of this city is a goddess whose name in the Egyptian tongue is Neith, and in Greek, as the Egyptians say, Athena.  The people of Sais are great lovers of the Athenians, and claim a certain kinship with them.</p></p>
<p>When Solon visited this city he was most honorably entreated by its people, and when he inquired concerning ancient things of the priests who were most learned therein, he found that he nor any other Greek knew anything about such matters.  And when he wished to lead them on to talk of ancient times, he told them of the oldest legends of Greece, of Phoroneus, who was called the first man, and of Niobe, of the tale of Deucalion and Pyrrha, how they survived after the deluge, and he reckoned up their descendants, and tried, by calculating the periods, to count up the number of years that passed during the events he related.</p>
<p>Then one of the priests, a man well stricken in years, said: &#147;Solon, Solon, you Greeks are but children.&#148;</p>
<p>&#147;What do you mean?&#148; asked Solon.</p>
<p>&#147;You are all young in your souls, for you have not any old tradition, any ancient belief, nor any knowledge that is hoary with age.  And the reason of it is this: many have been the destructions of mankind, and many shall be.  The greatest are by fire and by water, but besides these are lesser ones.  For indeed, the tale that is also told among you - how that Phaethon yoked his father's chariot, and, for that he could not drive in his father's path, he bunt up all things upon earth and was himself smitten by a thunderbolt and slain - this story has the air of a fable.  But the truth concerning it is related to the deviation of the bodies that move around the earth in the heavens, whereby at long intervals of time a destruction through fire of the things that are upon earth occurs.  But the legends preserved here are the most ancient on record.  The truth is that in all places, where great cold or heat does not forbid, there are always human beings, sometimes more, sometimes fewer, and whether at Athens or in Egypt or in any other known place anything noble or great or otherwise notable has occurred, we have written down and preserved an account of it from ancient times in our temple.  But with you and other nations the commonwealth has only just been discovered - the use of letters and the other commodities that cities require - and after the wonted number of years, like a recurring sickness, comes a rushing torrent from heaven, leaving only the unlettered and untaught among you, so that, as it were, you become young again, knowing nothing about what happened in ancient times either in our country or in yours.</p>
<p>&#147;For example, these genealogies, Solon, which you have just now recounted of the people of your country, are little better than children's tales.  In the first place you remember but one deluge, whereas there have been many before it.  Once upon a time, Solon, far back beyond the greatest destruction by waters, that which is now the city of the Athenians was foremost in war and indeed all other things.  Her laws were exceedingly righteous, and her deeds and government are said to have been the noblest.&#148;</p>
<p>Solon was astonished on hearing this, and used all urgency in entreating the priest to relate to him from beginning to end all about these ancient citizens.</p>
<p>So the priest said: &#147;Solon, I will tell it for your sake and for the sake of your city, and for the honor of the goddess who was the owner and nurse and instructress both of your city and of ours, for she founded yours earlier by a thousand years, having taken the seed of you from Earth and Hephaistos, and ours in a later time.  And the date of our city's foundation is recorded in our sacred writings to be eight thousand years ago.  But concerning the citizens of Athens nine thousand years ago, I will briefly inform you of the noblest of the deeds which they performed.</p>
<p>&#147;Our chronicles tell of a great adversary your city conquered, a power which advanced in wanton insolence upon all Europe and Asia together, issuing yonder from the Atlantic Ocean.  For in those days the sea there could be crossed, since it had an island before the mouth of the straight, which is called, as you say, the Pillars of Hercules.  This island, Atlantis, was greater than North Africa and Asia Minor together, and, therefrom, there was a passage for the seafarers of those times to the other islands, and from the islands to the opposite continent.  And in Atlantis arose a great and marvelous might of kings, ruling over all the island itself, and many other islands, and North Africa as far as Egypt, and Europe to the borders of Eturia.  So all this power gathered itself together and sought, with one single swoop, to enslave your country and ours and the whole region within the straight.  Then, Solon, did the power of your city shine forth in all men's eyes, glorious in valor and strength.  Being foremost upon earth in courage and the arts of war, Athena - sometimes the leader of the Hellenes, sometimes standing alone perforce when the rest fell away from her - after being brought into the uttermost perils, vanquished the invaders and triumphed over them, and the nations that were not yet enslaved she preserved from slavery, and the rest of us who dwell this side the Pillars of Hercules she set free with ungrudging hand.  But in later time, after there had been exceeding great earthquakes and floods, there fell one day and night of destruction; and the warriors in your land all in one body were swallowed up by the earth, and in like manner did the island Atlantis sink beneath the sea and vanish away.  Wherefore to this day the ocean there is impassible and unsearchable, being blocked by very shallow shoals, which the island caused as she settled down.&#148;</p>
</div>
