<?php
// DO NOT CHANGE INDEXES!
// flavors are stored in DB by index number

// last value = 47
$FLAVORS = array(
  0 => '-',

  1 => 'Aging Root',
  2 => 'Apricot',
  3 => 'Artichoke',
  4 => 'Azuki Bean',
  36 => 'Baking Chocolate',
  5 => 'Banana',
  44 => 'Barley',
  6 => 'Beet',
  7 => 'Blueberries',
  8 => 'Butter',
  9 => 'Carrot',
  10 => 'Celery',
  11 => 'Cheese',
  12 => 'Chicken',
  46 => 'Cinnamon',
  13 => 'Coconut',
  14 => 'Corn',
  37 => 'Cream Cheese',
  15 => 'Delicious',
  16 => 'Eggplant',
  17 => 'Fish',
  42 => 'Hops',
  18 => 'Mango',
  19 => 'Milk',
  45 => 'Nutmeg',
  20 => 'Onion',
  21 => 'Orange',
  22 => 'Pamplemousse',
  23 => 'Pineapple',
  39 => 'Pork',
  24 => 'Potato',
  25 => 'Prickly Green',
  26 => 'Redsberries',
  43 => 'Rye',
  27 => 'Seaweed',
  38 => 'Sour Cream',
  28 => 'Sour Lime',
  29 => 'Soy Bean',
  30 => 'Steak',
  47 => 'Sugardew',
  31 => 'Tomato',
  32 => 'Vinegar',
  33 => 'Watermelon',
  40 => 'Wheat',
  34 => 'White Radish',
  41 => 'Wild Oats',
  35 => 'Yam',
);

$COLORS = array(
  'none', 'red', 'orange', 'yellow', 'green', 'blue', 'purple', 'pink', 'white', 'black',
);
