<?php
$categories = array(
  'all' => false,
  'animal' => false,
  'armament' => array(
    'all' => false,
    'armor' => false,
    'helmet' => false,
    'shield' => false,
    'weapon' => array(
      'all' => false,
      'axe' => false,
      'bow' => false,
      'club' => false,
      'dagger' => false,
      'hammer' => false,
      'hypertech' => false,
      'staff' => false,
      'sword' => false,
      'wand' => false,
    ),
  ),
  'clothing' => array(
    'all' => false,
    'cape' => false,
    'costume' => false,
    'hat' => false,
  ),
  'construction' => array(
    'all' => false,
    'roof' => false,
    'wall' => false,
  ),
  'craft' => array(
    'all' => false,
    'figurine' => false,
    'furniture' => false,
    'instrument' => false,
    'jewelry' => array(
      'all' => false,
      'bracelet' => false,
      'earrings' => false,
      'necklace' => false,
      'ring' => false,
    ),
    'painting' => false,
    'plush' => false,
    'sculpture' => array(
      'all' => false,
      'totem' => false,
    ),
    'wallpaper' => false,
  ),
  'divine' => false,
  'earth' => array(
    'all' => false,
    'metal' => false,
    'mineral' => false,
  ),
  'electronic' => array(
    'all' => false,
    'circuit' => false,
  ),
  'food' => array(
    'all' => false,
    'baked' => false,
    'candy' => false,
    'dairy' => false,
    'egg' => false,
    'fruit' => false,
    'meat' => false,
    'prepared' => array(
      'all' => false,
      'delicacy' => false,
      'sandwich' => false,
      'tea' => false,
    ),
    'vegetable' => false,
  ),
  'forge' => array(
    'all' => false,
    'cloth' => false,
    'dye' => false,
    'materia' => false,
  ),
  'magic' => array(
    'all' => false,
    'abjuration' => false,
    'alteration' => false,
    'divination' => false,
  ),
  'plant' => array(
    'all' => false,
    'leaf' => false,
    'tree' => false,
  ),
  'print' => array(
    'all' => false,
    'blueprint' => false,
    'book' => array(
      'all' => false,
      'fiction' => false,
      'play' => false,
      'recipe' => false,
    ),
    'deed' => false,
    'scroll' => false,
  ),
  'tool' => array(
    'all' => false,
    'hammer' => false,
    'key' => false,
    'knife' => false,
    'light' => false,
    'shovel' => false,
    'staff' => false,
  ),
  'toy' => array(
    'all' => false,
    'chess' => false,
    'construction' => false,
    'game' => false,
    'mahjong' => false,
  ),
  'misc.' => false,
);
?>
