<?php
$transformations = array(
  'Shrinky Ray Gun' => 'Expandy Ray Gun',
  'Small Giamond' => 'Large Giamond',
  'Small Gemerald' => 'Large Gemerald',
  'Small Gemuline' => 'Large Gemuline',
  'Tiny Ornithopter' => 'Ornithopter',
  'Pitless Peach' => 'Giant Peach',
  'Egg' => 'Gargantuan Egg',
  'Small Rock' => 'Large Rock',
  'Large Rock' => 'Really Enormously Tremendous Rock',
  '4-Sided Die' => '6-Sided Die',
  '6-Sided Die' => '8-Sided Die',
  '4-Function Calculator' => '5-Function Calculator',
  'The World\'s Tiniest Violin' => 'Violin',
  'Small TV' => 'Big TV',
  'Tiny Unlocked Chest' => 'Treasure Chest', // both are Wand of Wonder items
  'Small Locked Chest' => 'Locked Chest',
  'Locked Chest' => 'Over-Sized Locked Chest',
  'Small Black Umbrella' => 'Large Black Umbrella',
  'Small Giamond Ring' => 'Large Giamond Ring',
  'Reasonably-Sized Sword' => 'Unreasonably Large Sword',
  'Propeller' => 'Large Propeller',
  'Modest Wooden Mallet' => 'Large Wooden Mallet',
  'Paper Boat' => 'Large Paper Boat',
  'Short Sword' => 'Great Sword',
  'Audio CD' => 'Laserdisc',
  'Silver Bell' => 'Tower Bell',
  'Gearbox' => 'Large Gearbox',
  'Net' => 'Big Net',
  'Red-striped Cloth' => 'Large Red-striped Sheet',
  'Short Bone' => 'Long Bone',
  'Kumquat' => 'Orange',
  'Orange' => 'Pamplemousse',
  'Pamplemousse' => 'Pomelo',
  'Shallot' => 'Onion',
  '2-Leaf Clover' => '3-Leaf Clover',
  '3-Leaf Clover' => '4-Leaf Clover',
  '4-Leaf Clover' => '5-Leaf Clover',
);

$addons = array(
  'Airship Mooring', 'Apiary', 'Aquarium', 'Attic', 'Basement', 'Colossus', 'Dungeon',
  'Eiffel Tower', 'Fiberoptic Link', 'Fireplace', 'Forge', 'Hungry Sidewalk',
  'Indoor Swimming Pool', 'Lake', 'Library', 'Map Room', 'Menagerie', 'Moat',
  'Refreshing Spring', 'Smokehouse', 'Tower', 'Windmill',
  'Wishing Well',
);
?>