INSERT INTO `monster_smith` VALUES (1, 'no', 'smith', 'Feathered Helmet,Antique Armor,Unholy Vorpal Sword of Southern Icereach,Elusive Shield of the Raging Werebear', 'Medieval Suit of Armor', 100);
INSERT INTO `monster_smith` VALUES (2, 'no', 'smith', 'White Pawn,White Pawn,White Pawn,White Pawn,White Pawn,White Pawn,White Pawn,White Pawn,White Rook,White Rook,White Knight,White Knight,White Bishop,White Bishop,White Queen,White King,Black Pawn,Black Pawn,Black Pawn,Black Pawn,Black Pawn,Black Pawn,Black Pawn,Black Pawn,Black Rook,Black Rook,Black Knight,Black Knight,Black Bishop,Black Bishop,Black Queen,Black King', 'Fancy Chess Set', 1000);
INSERT INTO `monster_smith` VALUES (4, 'no', 'smith', 'Small Gemerald,Small Gemerald', 'Large Gemerald', 30);
INSERT INTO `monster_smith` VALUES (5, 'no', 'smith', 'Small Gemuline,Small Gemuline', 'Large Gemuline', 30);
INSERT INTO `monster_smith` VALUES (6, 'no', 'smith', 'Small Giamond,Small Giamond', 'Large Giamond', 30);
INSERT INTO `monster_smith` VALUES (8, 'yes', 'smith', 'PsyPets Ticket', 'Shelly Plushy', 0);
INSERT INTO `monster_smith` VALUES (9, 'yes', 'smith', 'PsyPets Ticket', 'Figurine #1', 0);
INSERT INTO `monster_smith` VALUES (10, 'yes', 'smith', 'PsyPets Ticket', 'Spork', 0);
INSERT INTO `monster_smith` VALUES (11, 'yes', 'smith', 'PsyPets Ticket', 'Ring of Regeneration +1', 0);
INSERT INTO `monster_smith` VALUES (12, 'yes', 'smith', 'Spork', 'Foon', 1000);
INSERT INTO `monster_smith` VALUES (13, 'yes', 'smith', 'Foon', 'Spork', 1000);
INSERT INTO `monster_smith` VALUES (14, 'yes', 'smith', 'Gold Ring,Gossamer,Turtle Plushy', 'Shelly Plushy', 250);
INSERT INTO `monster_smith` VALUES (17, 'yes', 'smith', 'Black Pawn,Black Pawn', 'Black Queen', 0);
INSERT INTO `monster_smith` VALUES (18, 'yes', 'smith', 'Black Pawn,Black Pawn', 'Black Rook', 0);
INSERT INTO `monster_smith` VALUES (19, 'yes', 'smith', 'Black Pawn,Black Pawn', 'Black Bishop', 0);
INSERT INTO `monster_smith` VALUES (20, 'yes', 'smith', 'Black Pawn,Black Pawn', 'Black Knight', 0);
INSERT INTO `monster_smith` VALUES (21, 'yes', 'smith', 'White Pawn,White Pawn', 'White Queen', 0);
INSERT INTO `monster_smith` VALUES (22, 'yes', 'smith', 'White Pawn,White Pawn', 'White Rook', 0);
INSERT INTO `monster_smith` VALUES (23, 'yes', 'smith', 'White Pawn,White Pawn', 'White Bishop', 0);
INSERT INTO `monster_smith` VALUES (24, 'yes', 'smith', 'White Pawn,White Pawn', 'White Knight', 0);
INSERT INTO `monster_smith` VALUES (29, 'yes', 'smith', 'Cauldron', 'Pot of Gold', 1000);
INSERT INTO `monster_smith` VALUES (30, 'yes', 'smith', 'Red Dye,Egg', 'Red-Dyed Egg', 6);
INSERT INTO `monster_smith` VALUES (31, 'yes', 'smith', 'Blue Dye,Egg', 'Blue-Dyed Egg', 6);
INSERT INTO `monster_smith` VALUES (32, 'yes', 'smith', 'Yellow Dye,Egg', 'Yellow-Dyed Egg', 6);
INSERT INTO `monster_smith` VALUES (33, 'yes', 'smith', 'Figurine #4,Gossamer,Silver Tiara', 'Figurine #4 Special Edition', 250);
INSERT INTO `monster_smith` VALUES (34, 'yes', 'smith', 'Small White Pillow,Gossamer,Red Dye,Yellow Dye,Blue Dye', 'Dragon Pillow', 250);
INSERT INTO `monster_smith` VALUES (35, 'yes', 'smith', 'Simple Circuit,4-Function Calculator', '5-Function Calculator', 5);
INSERT INTO `monster_smith` VALUES (36, 'yes', 'smith', 'Gold Ring,Small Giamond', 'Small Giamond Ring', 60);
INSERT INTO `monster_smith` VALUES (37, 'yes', 'smith', 'Gold Ring,Large Giamond', 'Large Giamond Ring', 75);
INSERT INTO `monster_smith` VALUES (39, 'yes', 'smith', 'Unholy Vorpal Sword of Southern Icereach,Unholy Vorpal Sword of Southern Icereach,Light Saber,Gossamer', 'Vorpal Saber +1/+3 vs Chinchilla', 50);
INSERT INTO `monster_smith` VALUES (40, 'yes', 'smith', 'White Fan,Red Dye', 'Red Fan', 9);
INSERT INTO `monster_smith` VALUES (41, 'yes', 'smith', 'White Fan,Yellow Dye,Blue Dye', 'Green Fan', 9);
INSERT INTO `monster_smith` VALUES (42, 'yes', 'smith', 'White Fan,Red Dye,Yellow Dye', 'Orange Fan', 9);
INSERT INTO `monster_smith` VALUES (45, 'yes', 'smith', 'Gossamer,Smoke,Red Dye,Yellow Dye', 'Shimoku Plushy', 250);
INSERT INTO `monster_smith` VALUES (46, 'yes', 'smith', 'Unreasonably Large Sword,Medieval Suit of Armor,Dragon-in-a-Can', 'Panzie Action Figure', 200);
INSERT INTO `monster_smith` VALUES (47, 'yes', 'smith', 'Flower Painting,Palette', 'Scenery Painting', 20);
INSERT INTO `monster_smith` VALUES (49, 'yes', 'smith', 'Ring of Regeneration +1,Ring of Regeneration +1', 'Ring of Regeneration +2', 500);
INSERT INTO `monster_smith` VALUES (50, 'yes', 'smith', 'Plain Metal Block,Gossamer,Gold Ring', 'Question Mark Block', 0);
INSERT INTO `monster_smith` VALUES (56, 'yes', 'smith', 'Ring of Regeneration +1/3,Ring of Regeneration +1/3,Ring of Regeneration +1/3,Gossamer', 'Ring of Regeneration +1', 5000);
INSERT INTO `monster_smith` VALUES (57, 'yes', 'smith', 'Pearl', 'Star of Pearl', 50);
INSERT INTO `monster_smith` VALUES (58, 'yes', 'smith', 'The Writ of Chaos: The Whole of Creation,The Writ of Chaos: The Forging of Chaos,The Writ of Chaos: The Semblances on Earth,The Writ of Chaos: The Wills of Change and Consistency in Humans', 'The Writ of Chaos', 0);
INSERT INTO `monster_smith` VALUES (64, 'yes', 'smith', 'Sculpting Knife,Small Giamond', 'Giamond-Blade Knife', 50);
INSERT INTO `monster_smith` VALUES (75, 'yes', 'smith', 'Yellow Dye,Red Dye,Blue Dye,Egg', 'Rainbow-Dyed Egg', 6);
INSERT INTO `monster_smith` VALUES (76, 'no', 'smith', '6-Sided Die,6-Sided Die,6-Sided Die,Paper,Paper,Black Dye,Black Dye', 'Story Teller Screen', 50);
INSERT INTO `monster_smith` VALUES (81, 'yes', 'smith', 'White Pawn,Black Dye', 'Black Pawn', 50);
INSERT INTO `monster_smith` VALUES (82, 'yes', 'smith', 'World Map #1,World Map #2,World Map #3,World Map #4', 'Complete Map', 25);
INSERT INTO `monster_smith` VALUES (112, 'no', 'smith', 'Paper,Blue Dye', 'Complex Circuit Blueprint', 10);
INSERT INTO `monster_smith` VALUES (113, 'no', 'smith', 'Rubber,Talon', 'White Paint', 10);
INSERT INTO `monster_smith` VALUES (114, 'yes', 'smith', 'Paper,Blue Dye', 'Skeleton Key Blueprint', 10);
INSERT INTO `monster_smith` VALUES (115, 'no', 'smith', 'Coal,Coal,Coal', 'Small Giamond', 10);
INSERT INTO `monster_smith` VALUES (116, 'yes', 'smith', 'Coal', 'Black Dye', 5);
INSERT INTO `monster_smith` VALUES (117, 'no', 'smith', 'Paper,Blue Dye', 'Attic Blueprint', 10);
INSERT INTO `monster_smith` VALUES (118, 'no', 'smith', 'Paper,Blue Dye', 'Greenhouse Blueprint', 10);
INSERT INTO `monster_smith` VALUES (119, 'yes', 'smith', 'White PsyPod,Black Dye,Black Dye', 'Black PsyPod', 0);
INSERT INTO `monster_smith` VALUES (120, 'yes', 'smith', 'White PsyPod,Red Dye,Red Dye', 'Red PsyPod', 0);
INSERT INTO `monster_smith` VALUES (121, 'yes', 'smith', 'White PsyPod,Red Dye,Yellow Dye', 'Orange PsyPod', 0);
INSERT INTO `monster_smith` VALUES (122, 'yes', 'smith', 'White PsyPod,Yellow Dye,Yellow Dye', 'Yellow PsyPod', 0);
INSERT INTO `monster_smith` VALUES (123, 'yes', 'smith', 'White PsyPod,Blue Dye,Yellow Dye', 'Green PsyPod', 0);
INSERT INTO `monster_smith` VALUES (124, 'yes', 'smith', 'White PsyPod,Blue Dye,Blue Dye', 'Blue PsyPod', 0);
INSERT INTO `monster_smith` VALUES (125, 'yes', 'smith', 'White PsyPod,Red Dye,Blue Dye', 'Purple PsyPod', 0);
INSERT INTO `monster_smith` VALUES (126, 'yes', 'smith', 'White PsyPod,Red Dye,Red Dye', 'Pink PsyPod', 0);
INSERT INTO `monster_smith` VALUES (127, 'no', 'tailor', 'White Cloth,White Cloth,White Cloth,Fluff,Fluff', 'Ghost in a Blanket Costume', 200);
INSERT INTO `monster_smith` VALUES (128, 'no', 'tailor', 'Foil,Wood,Eye Patch,Red Cloth,Red Cloth,White Cloth,White Cloth', 'Pirate Costume', 1000);
INSERT INTO `monster_smith` VALUES (129, 'no', 'tailor', 'Staff of Stars and Moons,Silver Tiara,White Cloth,White Cloth,White Cloth,White Cloth,Fluff,Red Dye,Leather,Rubber,Tin,Black Dye,Black Dye', 'Tap Dancing Ballerina Fairy Princess Veterinarian Costume', 1500);
INSERT INTO `monster_smith` VALUES (130, 'no', 'tailor', 'Dirty Linen', 'White Cloth', 5);
INSERT INTO `monster_smith` VALUES (131, 'no', 'tailor', 'Collared Black Cape,Crystal Bangle,Unreasonably Large Sword,Fluff,Fluff,Yellow Dye,Yellow Dye', 'Angsty Anime Hero Costume', 1000);
INSERT INTO `monster_smith` VALUES (132, 'no', 'alchemy', '40|Silver Tiara,20|Tea Kettle|10 Folding Table', 'Loaf', 0);
INSERT INTO `monster_smith` VALUES (133, 'no', 'alchemy', '30|White Fan,25|Model Calabi-Yau Manifold,25|Model Molecule', 'Magic Pixie Dust', 0);
INSERT INTO `monster_smith` VALUES (134, 'no', 'alchemy', '25|Couch,15|Small Couch,10|Small Blue Couch', 'Child''s Play', 0);
INSERT INTO `monster_smith` VALUES (135, 'no', 'alchemy', '40|Spyglass,20|Metal Detector', 'Child''s Play', 0);
INSERT INTO `monster_smith` VALUES (136, 'no', 'alchemy', '15|Windup Gator', 'Scroll of Monster Summoning', 0);
INSERT INTO `monster_smith` VALUES (137, 'no', 'alchemy', '5|Hammock', 'Scroll of Monster Summoning', 0);
INSERT INTO `monster_smith` VALUES (138, 'no', 'alchemy', '20|Planetarium Projector,20|Sunshine Chair', 'Atrophy', 0);
INSERT INTO `monster_smith` VALUES (139, 'no', 'alchemy', '20|Comfy Chair,20|Serpent''s Bite', 'Stumble', 0);
INSERT INTO `monster_smith` VALUES (140, 'no', 'alchemy', '20|Leather Chair,10|Gaudy Chair', 'Forget', 0);
INSERT INTO `monster_smith` VALUES (142, 'no', 'smith', 'Paper,Blue Dye', 'Tower Blueprint', 15);
INSERT INTO `monster_smith` VALUES (143, 'yes', 'smith', 'Log,Red Dye', 'Angry Totem', 20);
INSERT INTO `monster_smith` VALUES (145, 'no', 'smith', 'Baking Chocolate,Baking Chocolate,Sugar,Rubble', 'Chocolate Egg', 10);
