INSERT INTO `monster_recipes` VALUES (1, 'Red Jelly,White Bread', 'Red Jelly on White Bread');
INSERT INTO `monster_recipes` VALUES (2, 'Purple Jelly,White Bread', 'Purple Jelly on White Bread');
INSERT INTO `monster_recipes` VALUES (3, 'Red Jelly,Wheat Bread', 'Red Jelly on Wheat Bread');
INSERT INTO `monster_recipes` VALUES (4, 'Purple Jelly,Wheat Bread', 'Purple Jelly on Wheat Bread');
INSERT INTO `monster_recipes` VALUES (5, 'Blueberries,Blueberries', 'Purple Jelly');
INSERT INTO `monster_recipes` VALUES (6, 'Egg,White Bread', 'Egg on White Bread');
INSERT INTO `monster_recipes` VALUES (7, 'Egg,Wheat Bread', 'Egg on Wheat Bread');
INSERT INTO `monster_recipes` VALUES (8, 'Blue Egg,White Bread', 'Blue Egg on White Bread');
INSERT INTO `monster_recipes` VALUES (9, 'Blue Egg,Wheat Bread', 'Blue Egg on Wheat Bread');
INSERT INTO `monster_recipes` VALUES (10, 'Blue Egg,Fire Spice,Ginger', 'Recherche Devilled Eggs');
INSERT INTO `monster_recipes` VALUES (11, 'Redsberries,Redsberries', 'Red Jelly');
INSERT INTO `monster_recipes` VALUES (12, 'Redsberries,Blueberries', 'Swirled Jelly');
INSERT INTO `monster_recipes` VALUES (13, 'Swirled Jelly,White Bread', 'Swirled Jelly on White Bread');
INSERT INTO `monster_recipes` VALUES (14, 'Swirled Jelly,Wheat Bread', 'Swirled Jelly on Wheat Bread');
INSERT INTO `monster_recipes` VALUES (15, 'Tea Leaves', 'Tea');
INSERT INTO `monster_recipes` VALUES (16, 'Tea Leaves,Ginger', 'Ginger Tea');
INSERT INTO `monster_recipes` VALUES (17, 'Tea Leaves,Orange', 'Orange Tea');
INSERT INTO `monster_recipes` VALUES (18, 'Redsberries,Tea Leaves', 'Berry Tea');
INSERT INTO `monster_recipes` VALUES (19, 'Blueberries,Tea Leaves', 'Berry Tea');
INSERT INTO `monster_recipes` VALUES (20, 'Speckled Egg,White Bread', 'Egg on White Bread');
INSERT INTO `monster_recipes` VALUES (21, 'Speckled Egg,Wheat Bread', 'Egg on Wheat Bread');
INSERT INTO `monster_recipes` VALUES (22, 'Tea Leaves,Sugar', 'Sweet Tea');
INSERT INTO `monster_recipes` VALUES (23, 'Tea Leaves,Ginger,Sugar', 'Sweet Ginger Tea');
INSERT INTO `monster_recipes` VALUES (24, 'Tea Leaves,Orange,Sugar', 'Sweet Orange Tea');
INSERT INTO `monster_recipes` VALUES (25, 'Redsberries,Tea Leaves,Sugar', 'Sweet Berry Tea');
INSERT INTO `monster_recipes` VALUES (26, 'Blueberries,Tea Leaves,Sugar', 'Sweet Berry Tea');
INSERT INTO `monster_recipes` VALUES (27, 'Blueberries,Blueberries,Sugar', 'Purple Jelly');
INSERT INTO `monster_recipes` VALUES (28, 'Redsberries,Redsberries,Sugar', 'Red Jelly');
INSERT INTO `monster_recipes` VALUES (29, 'Redsberries,Blueberries,Sugar', 'Swirled Jelly');
INSERT INTO `monster_recipes` VALUES (30, 'Orange,Orange', 'Orange Juice');
INSERT INTO `monster_recipes` VALUES (31, 'Prickly Green,Prickly Green', 'Prickly Green Juice');
INSERT INTO `monster_recipes` VALUES (32, 'Ginger Tea,Sugar', 'Sweet Ginger Tea');
INSERT INTO `monster_recipes` VALUES (33, 'Tea,Sugar', 'Sweet Tea');
INSERT INTO `monster_recipes` VALUES (34, 'Orange Tea,Sugar', 'Sweet Orange Tea');
INSERT INTO `monster_recipes` VALUES (35, 'Berry Tea,Sugar', 'Sweet Berry Tea');
INSERT INTO `monster_recipes` VALUES (36, 'Fire Spice,Tea Leaves', 'Fire Spice Tea');
INSERT INTO `monster_recipes` VALUES (37, 'Fire Spice,Tea Leaves,Sugar', 'Sweet Fire Spice Tea');
INSERT INTO `monster_recipes` VALUES (38, 'Fire Spice Tea,Sugar', 'Sweet Fire Spice Tea');
INSERT INTO `monster_recipes` VALUES (39, 'Flour,Sugar,Egg,Milk,Blueberries', 'Blueberry Muffin,Blueberry Muffin,Blueberry Muffin');
INSERT INTO `monster_recipes` VALUES (40, 'Flour,Sugar,Egg,Milk,Redsberries', 'Redsberry Muffin,Redsberry Muffin,Redsberry Muffin');
INSERT INTO `monster_recipes` VALUES (41, 'Flour,Sugar,Egg,Milk', 'Muffin,Muffin,Muffin');
INSERT INTO `monster_recipes` VALUES (42, 'Flour,Sugar,Speckled Egg,Milk,Blueberries', 'Blueberry Muffin,Blueberry Muffin,Blueberry Muffin');
INSERT INTO `monster_recipes` VALUES (43, 'Flour,Sugar,Speckled Egg,Milk,Redsberries', 'Redsberry Muffin,Redsberry Muffin,Redsberry Muffin');
INSERT INTO `monster_recipes` VALUES (44, 'Flour,Sugar,Speckled Egg,Milk', 'Muffin,Muffin,Muffin');
INSERT INTO `monster_recipes` VALUES (45, 'Orange,Chicken', 'Orange Chicken');
INSERT INTO `monster_recipes` VALUES (46, 'Sugar,Butter,Egg,Flour', 'Sugar Cookies,Sugar Cookies,Sugar Cookies,Sugar Cookies,Sugar Cookies');
INSERT INTO `monster_recipes` VALUES (47, 'Corn', 'Popped Corn');
INSERT INTO `monster_recipes` VALUES (48, 'Corn,Butter', 'Buttered Corn');
INSERT INTO `monster_recipes` VALUES (49, 'Popped Corn,Butter', 'Buttered Popped Corn');
INSERT INTO `monster_recipes` VALUES (50, 'Sugar,Popped Corn', 'Kettle Corn');
INSERT INTO `monster_recipes` VALUES (51, 'Red Jelly,Purple Jelly', 'Swirled Jelly,Swirled Jelly');
INSERT INTO `monster_recipes` VALUES (52, 'Flour,Sugar,Egg,Milk,Baking Chocolate', 'Chocolate Donut,Chocolate Donut,Chocolate Donut,Chocolate Donut');
INSERT INTO `monster_recipes` VALUES (53, 'Sugar,Baking Chocolate', 'Chocolate Drops,Chocolate Drops,Chocolate Drops');
INSERT INTO `monster_recipes` VALUES (54, 'Flour,Sugar,Egg,Milk,Sugar', 'Sprinkled Donut,Sprinkled Donut,Sprinkled Donut,Sprinkled Donut');
INSERT INTO `monster_recipes` VALUES (55, 'Sugar,Butter,Egg,Flour,Chocolate Drops', 'Chocolate Chip Cookies,Chocolate Chip Cookies,Chocolate Chip Cookies,Chocolate Chip Cookies,Chocolate Chip Cookies');
INSERT INTO `monster_recipes` VALUES (56, 'Butter,Flour,Sugar', 'Shortbread,Shortbread,Shortbread');
INSERT INTO `monster_recipes` VALUES (57, 'Sugar,Flour,Shortening,Egg,Milk', 'Shortcake');
INSERT INTO `monster_recipes` VALUES (58, 'Sugar,Flour,Shortening,Egg,Milk,Redsberries', 'Redsberry Shortcake');
INSERT INTO `monster_recipes` VALUES (59, 'Sugar,Flour,Shortening,Egg,Milk,Blueberries', 'Blueberry Shortcake');
INSERT INTO `monster_recipes` VALUES (60, 'Blueberries,Shortcake', 'Blueberry Shortcake');
INSERT INTO `monster_recipes` VALUES (61, 'Redsberries,Shortcake', 'Redsberry Shortcake');
INSERT INTO `monster_recipes` VALUES (62, 'Sugar,Flour,Egg,Milk,Butter', 'Shortcake');
INSERT INTO `monster_recipes` VALUES (63, 'Sugar,Flour,Egg,Milk,Redsberries,Butter', 'Redsberry Shortcake');
INSERT INTO `monster_recipes` VALUES (64, 'Sugar,Flour,Egg,Milk,Blueberries,Butter', 'Blueberry Shortcake');
INSERT INTO `monster_recipes` VALUES (65, 'Milk,Baking Chocolate,Sugar', 'Chocolate Milk,Chocolate Milk');
INSERT INTO `monster_recipes` VALUES (66, 'Sugar,Butter,Egg,Flour,Baking Chocolate', 'Brownie,Brownie,Brownie');
INSERT INTO `monster_recipes` VALUES (67, 'Butter,White Bread', 'Buttered White Bread');
INSERT INTO `monster_recipes` VALUES (68, 'Butter,Wheat Bread', 'Buttered Wheat Bread');
INSERT INTO `monster_recipes` VALUES (69, 'Cheese,White Bread', 'Cheese on White Bread');
INSERT INTO `monster_recipes` VALUES (70, 'Cheese,White Bread,Butter', 'Grilled Cheese on White');
INSERT INTO `monster_recipes` VALUES (71, 'Cheese,Buttered White Bread', 'Grilled Cheese on White');
INSERT INTO `monster_recipes` VALUES (72, 'Cheese,Wheat Bread', 'Cheese on Wheat Bread');
INSERT INTO `monster_recipes` VALUES (73, 'Cheese,Wheat Bread,Butter', 'Grilled Cheese on Wheat');
INSERT INTO `monster_recipes` VALUES (74, 'Cheese,Buttered Wheat Bread', 'Grilled Cheese on Wheat');
INSERT INTO `monster_recipes` VALUES (75, 'Sugar,Blueberries', 'Purple Taffy,Purple Taffy,Purple Taffy,Purple Taffy');
INSERT INTO `monster_recipes` VALUES (76, 'Sugar,Redsberries', 'Red Taffy,Red Taffy,Red Taffy,Red Taffy');
INSERT INTO `monster_recipes` VALUES (77, 'Sugar,Sugar,Orange', 'Orange Taffy,Orange Taffy,Orange Taffy,Orange Taffy,Orange Taffy,Orange Taffy,Orange Taffy,Orange Taffy');
INSERT INTO `monster_recipes` VALUES (78, 'Sugar,Sugar,Prickly Green', 'Green Taffy,Green Taffy,Green Taffy,Green Taffy,Green Taffy,Green Taffy,Green Taffy,Green Taffy');
INSERT INTO `monster_recipes` VALUES (79, 'Sugar,Sugar,Watermelon', 'Red Taffy,Green Taffy,Red Taffy,Green Taffy,Red Taffy,Green Taffy,Red Taffy,Green Taffy');
INSERT INTO `monster_recipes` VALUES (80, 'Broccoli,Cheese', 'Broccoli with Cheese');
INSERT INTO `monster_recipes` VALUES (81, 'Egg,Cheese', 'Omelette');
INSERT INTO `monster_recipes` VALUES (82, 'Speckled Egg,Cheese', 'Omelette');
INSERT INTO `monster_recipes` VALUES (83, 'Yeast,Flour,Sugar,Milk', 'White Bread,White Bread,White Bread,White Bread');
INSERT INTO `monster_recipes` VALUES (84, 'Yeast,Flour,Sugar,Milk,Butter', 'White Bread,White Bread,White Bread,White Bread,White Bread');
INSERT INTO `monster_recipes` VALUES (85, 'Yeast,Flour,Sugar,Milk,Shortening', 'White Bread,White Bread,White Bread,White Bread,White Bread');
INSERT INTO `monster_recipes` VALUES (86, 'Fish,Fire Spice,Ginger,Rice', 'Sushi');
INSERT INTO `monster_recipes` VALUES (87, 'Flour,Sugar,Speckled Egg,Milk,Chocolate Drops', 'Chocolate Chip Muffin,Chocolate Chip Muffin,Chocolate Chip Muffin');
INSERT INTO `monster_recipes` VALUES (88, 'Flour,Sugar,Egg,Milk,Chocolate Drops', 'Chocolate Chip Muffin,Chocolate Chip Muffin,Chocolate Chip Muffin');
INSERT INTO `monster_recipes` VALUES (89, 'Steak,BBQ Sauce', 'Steak BBQ');
INSERT INTO `monster_recipes` VALUES (90, 'Brown Sugar,Fire Spice,Ginger', 'BBQ Sauce,BBQ Sauce,BBQ Sauce,BBQ Sauce,BBQ Sauce,BBQ Sauce,BBQ Sauce,BBQ Sauce,BBQ Sauce,BBQ Sauce');
INSERT INTO `monster_recipes` VALUES (91, 'Chicken,BBQ Sauce', 'Chicken BBQ');
INSERT INTO `monster_recipes` VALUES (92, 'White Bread,Butter,Egg,Milk,Sugar', 'Bread Pudding,Bread Pudding,Bread Pudding,Bread Pudding');
INSERT INTO `monster_recipes` VALUES (93, 'Rice,Egg,Milk,Sugar', 'Rice Pudding,Rice Pudding,Rice Pudding,Rice Pudding');
INSERT INTO `monster_recipes` VALUES (94, 'Sugar,Butter,Speckled Egg,Flour', 'Sugar Cookies,Sugar Cookies,Sugar Cookies,Sugar Cookies,Sugar Cookies');
INSERT INTO `monster_recipes` VALUES (95, 'Sugar,Butter,Speckled Egg,Flour,Chocolate Drops', 'Chocolate Chip Cookies,Chocolate Chip Cookies,Chocolate Chip Cookies,Chocolate Chip Cookies,Chocolate Chip Cookies');
INSERT INTO `monster_recipes` VALUES (96, 'White Bread,Butter,Speckled Egg,Milk,Sugar', 'Bread Pudding,Bread Pudding,Bread Pudding,Bread Pudding');
INSERT INTO `monster_recipes` VALUES (97, 'Blueberries,Sugar,Milk', 'Blueberry Ice Cream,Blueberry Ice Cream');
INSERT INTO `monster_recipes` VALUES (98, 'Redsberries,Sugar,Milk', 'Redsberry Ice Cream,Redsberry Ice Cream');
INSERT INTO `monster_recipes` VALUES (99, 'Baking Chocolate,Sugar,Milk,Egg', 'Chocolate Ice Cream,Chocolate Ice Cream,Chocolate Ice Cream');
INSERT INTO `monster_recipes` VALUES (100, 'Chocolate Drops,Sugar,Milk,Egg', 'Chocolate Drop Ice Cream,Chocolate Drop Ice Cream,Chocolate Drop Ice Cream');
INSERT INTO `monster_recipes` VALUES (101, 'Baking Chocolate,Sugar,Milk,Speckled Egg', 'Chocolate Ice Cream,Chocolate Ice Cream,Chocolate Ice Cream');
INSERT INTO `monster_recipes` VALUES (102, 'Chocolate Drops,Sugar,Milk,Speckled Egg', 'Chocolate Drop Ice Cream,Chocolate Drop Ice Cream,Chocolate Drop Ice Cream');
INSERT INTO `monster_recipes` VALUES (103, 'Whole Pumpkin', 'Pumpkin Pieces,Pumpkin Pieces,Pumpkin Pieces,Raw Pumpkin Seeds');
INSERT INTO `monster_recipes` VALUES (104, 'Pumpkin Pieces,Milk,Egg,Brown Sugar,Ginger,Pie Crust', 'Pumpkin Pie');
INSERT INTO `monster_recipes` VALUES (105, 'Pumpkin Pieces,Milk,Egg,Sugar,Ginger,Pie Crust', 'Pumpkin Pie');
INSERT INTO `monster_recipes` VALUES (106, 'Pumpkin Pieces,Milk,Speckled Egg,Brown Sugar,Ginger,Pie Crust', 'Pumpkin Pie');
INSERT INTO `monster_recipes` VALUES (107, 'Pumpkin Pieces,Milk,Speckled Egg,Sugar,Ginger,Pie Crust', 'Pumpkin Pie');
INSERT INTO `monster_recipes` VALUES (108, 'Raw Pumpkin Seeds', 'Baked Pumpkin Seeds');
INSERT INTO `monster_recipes` VALUES (303, 'Pie Crust,Cheese,Speckled Egg,Milk,Steak,Onion', 'Quiche Alsacienne');
INSERT INTO `monster_recipes` VALUES (304, 'Egg,Tea Leaves,Sugar,Soy Sauce', 'Tea Egg');
INSERT INTO `monster_recipes` VALUES (302, 'Pie Crust,Cheese,Egg,Milk,Steak,Onion', 'Quiche Alsacienne');
INSERT INTO `monster_recipes` VALUES (300, 'Pie Crust,Cheese,Egg,Milk,Steak', 'Quiche Lorraine');
INSERT INTO `monster_recipes` VALUES (301, 'Pie Crust,Cheese,Speckled Egg,Milk,Steak', 'Quiche Lorraine');
INSERT INTO `monster_recipes` VALUES (298, 'Pie Crust,Cheese,Egg,Milk', 'Plain Quiche');
INSERT INTO `monster_recipes` VALUES (299, 'Pie Crust,Cheese,Speckled Egg,Milk', 'Plain Quiche');
INSERT INTO `monster_recipes` VALUES (113, 'Coconut', 'Coconut Meat,Coconut Meat,Coconut Juice');
INSERT INTO `monster_recipes` VALUES (114, 'Coconut,Ginger,Sour Lime,Chicken,Fire Spice', 'Tom Kah Gai,Tom Kah Gai,Coconut Meat,Coconut Meat');
INSERT INTO `monster_recipes` VALUES (115, 'Coconut Milk,Ginger,Sour Lime,Chicken,Fire Spice', 'Tom Kah Gai,Tom Kah Gai');
INSERT INTO `monster_recipes` VALUES (116, 'Sugar,Sour Lime', 'Green Taffy,Green Taffy,Green Taffy,Green Taffy');
INSERT INTO `monster_recipes` VALUES (117, 'Cheese on Wheat Bread,Butter', 'Grilled Cheese on Wheat');
INSERT INTO `monster_recipes` VALUES (118, 'Cheese on White Bread,Butter', 'Grilled Cheese on White');
INSERT INTO `monster_recipes` VALUES (119, 'Sour Lime,Sour Lime,Sugar', 'Limeade');
INSERT INTO `monster_recipes` VALUES (120, 'Grits', 'Hot Grits,Hot Grits,Hot Grits,Hot Grits');
INSERT INTO `monster_recipes` VALUES (121, 'Blueberries,Sugar,Mint Leaves', 'Mintberry Swirls,Mintberry Swirls');
INSERT INTO `monster_recipes` VALUES (122, 'Redsberries,Sugar,Mint Leaves', 'Mintberry Swirls,Mintberry Swirls');
INSERT INTO `monster_recipes` VALUES (123, 'Tea Leaves,Mint Leaves', 'Mint Tea');
INSERT INTO `monster_recipes` VALUES (124, 'Tea Leaves,Mint Leaves,Sugar', 'Sweet Mint Tea');
INSERT INTO `monster_recipes` VALUES (125, 'Mint Tea,Sugar', 'Sweet Mint Tea');
INSERT INTO `monster_recipes` VALUES (126, 'Steak,Egg,Onion', 'Salisbury Steak');
INSERT INTO `monster_recipes` VALUES (127, 'Steak,Speckled Egg,Onion', 'Salisbury Steak');
INSERT INTO `monster_recipes` VALUES (128, 'BBQ Sauce,Fish', 'Fish BBQ');
INSERT INTO `monster_recipes` VALUES (129, 'Chicken,Onion,Egg,Butter,White Bread', 'Chicken Kiev,Chicken Kiev');
INSERT INTO `monster_recipes` VALUES (130, 'Chicken,Onion,Egg,Butter,Wheat Bread', 'Chicken Kiev,Chicken Kiev');
INSERT INTO `monster_recipes` VALUES (131, 'Chicken,Onion,Speckled Egg,Butter,White Bread', 'Chicken Kiev,Chicken Kiev');
INSERT INTO `monster_recipes` VALUES (132, 'Chicken,Onion,Speckled Egg,Butter,Wheat Bread', 'Chicken Kiev,Chicken Kiev');
INSERT INTO `monster_recipes` VALUES (133, 'Egg,Milk,Butter,Sugar,Coconut Meat,Pie Crust', 'Coconut Pie');
INSERT INTO `monster_recipes` VALUES (134, 'Speckled Egg,Milk,Butter,Sugar,Coconut Meat,Pie Crust', 'Coconut Pie');
INSERT INTO `monster_recipes` VALUES (135, 'Butter,Brown Sugar', 'Caramel Squares,Caramel Squares,Caramel Squares,Caramel Squares,Caramel Squares');
INSERT INTO `monster_recipes` VALUES (136, 'Steak,Onion,White Bread,Fire Spice', 'Sloppy Joes');
INSERT INTO `monster_recipes` VALUES (137, 'Steak,Onion,Wheat Bread,Fire Spice', 'Sloppy Joes');
INSERT INTO `monster_recipes` VALUES (138, 'Butter,Sugar,Banana,Egg,Flour', 'Banana Bread');
INSERT INTO `monster_recipes` VALUES (139, 'Yam,Brown Sugar,Butter', 'Candied Yam');
INSERT INTO `monster_recipes` VALUES (140, 'Aging Root,Milk', 'Cheese');
INSERT INTO `monster_recipes` VALUES (141, 'Aging Root,Log', 'Mushroom');
INSERT INTO `monster_recipes` VALUES (142, 'Cream', 'Butter');
INSERT INTO `monster_recipes` VALUES (143, 'Aging Root,Egg', 'Rotten Egg');
INSERT INTO `monster_recipes` VALUES (144, 'Rice,Speckled Egg,Milk,Sugar', 'Rice Pudding,Rice Pudding,Rice Pudding,Rice Pudding');
INSERT INTO `monster_recipes` VALUES (145, 'Butter,Sugar', 'Caramel Squares,Caramel Squares,Caramel Squares,Caramel Squares,Caramel Squares');
INSERT INTO `monster_recipes` VALUES (146, 'Tea Leaves,Mint Leaves,Brown Sugar', 'Moroccan Mint,Moroccan Mint');
INSERT INTO `monster_recipes` VALUES (147, 'Popped Corn,Caramel Squares', 'Caramel Corn,Caramel Corn');
INSERT INTO `monster_recipes` VALUES (148, 'Buttered Popped Corn,Caramel Squares', 'Caramel Corn,Caramel Corn');
INSERT INTO `monster_recipes` VALUES (149, 'Kettle Corn,Caramel Squares', 'Caramel Corn,Caramel Corn');
INSERT INTO `monster_recipes` VALUES (150, 'Aging Root,Redsberries', 'Redsberry Wine');
INSERT INTO `monster_recipes` VALUES (151, 'Aging Root,Blueberries', 'Blueberry Wine');
INSERT INTO `monster_recipes` VALUES (152, 'Flour,Egg,White Bread,Onion', 'Onion Rings');
INSERT INTO `monster_recipes` VALUES (153, 'Flour,Egg,Wheat Bread,Onion', 'Onion Rings');
INSERT INTO `monster_recipes` VALUES (154, 'Delicious,Delicious', 'Apple Juice');
INSERT INTO `monster_recipes` VALUES (155, 'Delicious', 'Apple Sauce');
INSERT INTO `monster_recipes` VALUES (156, 'Tomato,Tomato', 'Tomato Sauce');
INSERT INTO `monster_recipes` VALUES (157, 'Tomato,Mushroom', 'Special Sauce');
INSERT INTO `monster_recipes` VALUES (158, 'Tomato,Steak', 'Beefy Tomato Sauce');
INSERT INTO `monster_recipes` VALUES (159, 'Tomato,Chicken', 'Tomato Sauce with Chicken');
INSERT INTO `monster_recipes` VALUES (160, 'Tomato,Mushroom,Steak', 'Special Beefy Sauce');
INSERT INTO `monster_recipes` VALUES (161, 'Tomato,Mushroom,Chicken', 'Special Sauce with Chicken');
INSERT INTO `monster_recipes` VALUES (162, 'Fish,Butter,Sour Lime', 'Lemon-Buttered Fish');
INSERT INTO `monster_recipes` VALUES (163, 'White Bread,Cheese,Tomato Sauce', 'Cheese Pizza');
INSERT INTO `monster_recipes` VALUES (164, 'Wheat Bread,Cheese,Tomato Sauce', 'Cheese Pizza');
INSERT INTO `monster_recipes` VALUES (165, 'White Bread,Cheese,Special Sauce', 'Cheese Pizza Supreme');
INSERT INTO `monster_recipes` VALUES (166, 'Wheat Bread,Cheese,Special Sauce', 'Cheese Pizza Supreme');
INSERT INTO `monster_recipes` VALUES (167, 'White Bread,Cheese,Beefy Tomato Sauce', 'Meat Pizza');
INSERT INTO `monster_recipes` VALUES (168, 'Wheat Bread,Cheese,Beefy Tomato Sauce', 'Meat Pizza');
INSERT INTO `monster_recipes` VALUES (169, 'White Bread,Cheese,Tomato Sauce with Chicken', 'Meat Pizza');
INSERT INTO `monster_recipes` VALUES (170, 'Wheat Bread,Cheese,Tomato Sauce with Chicken', 'Meat Pizza');
INSERT INTO `monster_recipes` VALUES (171, 'White Bread,Cheese,Chicken,Tomato Sauce', 'Meat Pizza');
INSERT INTO `monster_recipes` VALUES (172, 'Wheat Bread,Cheese,Chicken,Tomato Sauce', 'Meat Pizza');
INSERT INTO `monster_recipes` VALUES (173, 'White Bread,Cheese,Steak,Tomato Sauce', 'Meat Pizza');
INSERT INTO `monster_recipes` VALUES (174, 'Wheat Bread,Cheese,Steak,Tomato Sauce', 'Meat Pizza');
INSERT INTO `monster_recipes` VALUES (175, 'White Bread,Cheese,Special Beefy Sauce', 'Meat Pizza Supreme');
INSERT INTO `monster_recipes` VALUES (176, 'Wheat Bread,Cheese,Special Beefy Sauce', 'Meat Pizza Supreme');
INSERT INTO `monster_recipes` VALUES (177, 'White Bread,Cheese,Special Suace with Chicken', 'Meat Pizza Supreme');
INSERT INTO `monster_recipes` VALUES (178, 'Wheat Bread,Cheese,Special Suace with Chicken', 'Meat Pizza Supreme');
INSERT INTO `monster_recipes` VALUES (179, 'White Bread,Cheese,Chicken,Special Sauce', 'Meat Pizza Supreme');
INSERT INTO `monster_recipes` VALUES (180, 'Wheat Bread,Cheese,Chicken,Special Sauce', 'Meat Pizza Supreme');
INSERT INTO `monster_recipes` VALUES (181, 'White Bread,Cheese,Steak,Special Sauce', 'Meat Pizza Supreme');
INSERT INTO `monster_recipes` VALUES (182, 'Wheat Bread,Cheese,Steak,Special Sauce', 'Meat Pizza Supreme');
INSERT INTO `monster_recipes` VALUES (183, 'White Bread,Cheese,Chicken,Beefy Tomato Sauce', 'Meat Lover''s Pizza');
INSERT INTO `monster_recipes` VALUES (184, 'Wheat Bread,Cheese,Chicken,Beefy Tomato Sauce', 'Meat Lover''s Pizza');
INSERT INTO `monster_recipes` VALUES (185, 'White Bread,Cheese,Steak,Beefy Tomato Sauce', 'Meat Lover''s Pizza');
INSERT INTO `monster_recipes` VALUES (186, 'Wheat Bread,Cheese,Steak,Beefy Tomato Sauce', 'Meat Lover''s Pizza');
INSERT INTO `monster_recipes` VALUES (187, 'White Bread,Cheese,Chicken,Tomato Sauce with Chicken', 'Meat Lover''s Pizza');
INSERT INTO `monster_recipes` VALUES (188, 'Wheat Bread,Cheese,Chicken,Tomato Sauce with Chicken', 'Meat Lover''s Pizza');
INSERT INTO `monster_recipes` VALUES (189, 'White Bread,Cheese,Steak,Tomato Sauce with Chicken', 'Meat Lover''s Pizza');
INSERT INTO `monster_recipes` VALUES (190, 'Wheat Bread,Cheese,Steak,Tomato Sauce with Chicken', 'Meat Lover''s Pizza');
INSERT INTO `monster_recipes` VALUES (191, 'White Bread,Cheese,Chicken,Special Beefy Sauce', 'Meat Lover''s Pizza Supreme');
INSERT INTO `monster_recipes` VALUES (192, 'Wheat Bread,Cheese,Chicken,Special Beefy Sauce', 'Meat Lover''s Pizza Supreme');
INSERT INTO `monster_recipes` VALUES (193, 'White Bread,Cheese,Steak,Special Beefy Sauce', 'Meat Lover''s Pizza Supreme');
INSERT INTO `monster_recipes` VALUES (194, 'Wheat Bread,Cheese,Steak,Special Beefy Sauce', 'Meat Lover''s Pizza Supreme');
INSERT INTO `monster_recipes` VALUES (195, 'White Bread,Cheese,Chicken,Special Sauce with Chicken', 'Meat Lover''s Pizza Supreme');
INSERT INTO `monster_recipes` VALUES (196, 'Wheat Bread,Cheese,Chicken,Special Sauce with Chicken', 'Meat Lover''s Pizza Supreme');
INSERT INTO `monster_recipes` VALUES (197, 'White Bread,Cheese,Steak,Special Sauce with Chicken', 'Meat Lover''s Pizza Supreme');
INSERT INTO `monster_recipes` VALUES (198, 'Wheat Bread,Cheese,Steak,Special Sauce with Chicken', 'Meat Lover''s Pizza Supreme');
INSERT INTO `monster_recipes` VALUES (199, 'Sugar Beet', 'Sugar,Sugar,Brown Sugar');
INSERT INTO `monster_recipes` VALUES (200, 'Corn,Corn', 'Grits,Grits,Cornstarch,Cornstarch');
INSERT INTO `monster_recipes` VALUES (201, 'Coconut Meat', 'Coconut Milk');
INSERT INTO `monster_recipes` VALUES (202, 'Potato,Milk,Butter', 'Mashed Potatoes');
INSERT INTO `monster_recipes` VALUES (203, 'Raw Milk', 'Milk,Cream');
INSERT INTO `monster_recipes` VALUES (204, 'Blueberries', 'Blue Dye');
INSERT INTO `monster_recipes` VALUES (205, 'Potato,Sugar', 'Yeast,Yeast,Yeast,Yeast,Yeast,Yeast');
INSERT INTO `monster_recipes` VALUES (206, 'Steak', 'Jerky,Jerky,Jerky,Jerky');
INSERT INTO `monster_recipes` VALUES (207, 'Steak,Fire Spice', 'Spicy Jerky,Spicy Jerky,Spicy Jerky,Spicy Jerky');
INSERT INTO `monster_recipes` VALUES (208, 'Rubber', 'Plastic');
INSERT INTO `monster_recipes` VALUES (309, 'Baking Chocolate,Sugar,Rice', 'Crispy Crunchy Chocolate Chew,Crispy Crunchy Chocolate Chew,Crispy Crunchy Chocolate Chew,Crispy Crunchy Chocolate Chew');
INSERT INTO `monster_recipes` VALUES (262, 'White Bread,Peanuts,Chicken,Egg,Butter', 'Peanut-Crusted Chicken Breast,Peanut-Crusted Chicken Breast,Peanut-Crusted Chicken Breast');
INSERT INTO `monster_recipes` VALUES (211, 'Amethyst Rose', 'Red Dye,Red Dye');
INSERT INTO `monster_recipes` VALUES (212, 'Onion', 'Yellow Dye,Yellow Dye');
INSERT INTO `monster_recipes` VALUES (213, 'Aging Root,Raw Pumpkin Seeds', 'Whole Pumpkin');
INSERT INTO `monster_recipes` VALUES (214, 'Beet', 'Red Dye,Red Dye');
INSERT INTO `monster_recipes` VALUES (215, 'Duck Plushy,Coconut Juice', 'Duck Plushy Covered in Coconut Juice');
INSERT INTO `monster_recipes` VALUES (216, 'Gargantuan Egg,Cheese,Cheese', 'Omelette,Omelette');
INSERT INTO `monster_recipes` VALUES (217, 'Tea Leaves,Tea Leaves', 'Blue Dye,Yellow Dye');
INSERT INTO `monster_recipes` VALUES (218, 'Tomato', 'Red Dye,Red Dye');
INSERT INTO `monster_recipes` VALUES (219, 'Yeast,Redsberry Wine', 'Vinegar,Vinegar');
INSERT INTO `monster_recipes` VALUES (220, 'Yeast,Blueberry Wine', 'Vinegar,Vinegar');
INSERT INTO `monster_recipes` VALUES (221, 'Aging Root,Rice', 'Sake');
INSERT INTO `monster_recipes` VALUES (222, 'Potato,Aging Root', 'Vodka,Vodka');
INSERT INTO `monster_recipes` VALUES (223, 'Yeast,Vodka', 'Vinegar,Vinegar');
INSERT INTO `monster_recipes` VALUES (224, 'Yeast,Sake', 'Vinegar,Vinegar');
INSERT INTO `monster_recipes` VALUES (225, 'Sugar,Flour,Shortening,Speckled Egg,Milk', 'Shortcake');
INSERT INTO `monster_recipes` VALUES (226, 'Sugar,Flour,Shortening,Speckled Egg,Milk,Redsberries', 'Redsberry Shortcake');
INSERT INTO `monster_recipes` VALUES (227, 'Sugar,Flour,Shortening,Speckled Egg,Milk,Blueberries', 'Blueberry Shortcake');
INSERT INTO `monster_recipes` VALUES (228, 'Sugar,Flour,Speckled Egg,Milk,Butter', 'Shortcake');
INSERT INTO `monster_recipes` VALUES (229, 'Sugar,Flour,Speckled Egg,Milk,Redsberries,Butter', 'Redsberry Shortcake');
INSERT INTO `monster_recipes` VALUES (230, 'Sugar,Flour,Speckled Egg,Milk,Blueberries,Butter', 'Blueberry Shortcake');
INSERT INTO `monster_recipes` VALUES (231, 'Coconut,Aging Root', 'Minipalm');
INSERT INTO `monster_recipes` VALUES (232, 'Soy Bean', 'Edamame');
INSERT INTO `monster_recipes` VALUES (233, 'Soy Bean,Sugar,Aging Root', 'Soy Sauce,Soy Sauce');
INSERT INTO `monster_recipes` VALUES (234, 'Soy Bean,Brown Sugar,Aging Root', 'Soy Sauce,Soy Sauce');
INSERT INTO `monster_recipes` VALUES (235, 'Flour,Cornstarch,Sugar,Egg', 'Fortune Cookie,Fortune Cookie,Fortune Cookie,Fortune Cookie,Fortune Cookie,Fortune Cookie,Fortune Cookie');
INSERT INTO `monster_recipes` VALUES (236, 'Flour,Cornstarch,Sugar,Speckled Egg', 'Fortune Cookie,Fortune Cookie,Fortune Cookie,Fortune Cookie,Fortune Cookie,Fortune Cookie,Fortune Cookie');
INSERT INTO `monster_recipes` VALUES (237, 'Cornstarch', 'Oobleck');
INSERT INTO `monster_recipes` VALUES (238, 'Chicken,Onion,Ginger,Peanuts,Fire Spice,Soy Sauce,Sake,Cornstarch,Sugar', 'Gong Bao Chicken,Gong Bao Chicken,Gong Bao Chicken');
INSERT INTO `monster_recipes` VALUES (239, 'Chicken,Onion,Ginger,Peanuts,Fire Spice,Soy Sauce,Sake,Cornstarch,Brown Sugar', 'Gong Bao Chicken,Gong Bao Chicken,Gong Bao Chicken');
INSERT INTO `monster_recipes` VALUES (240, 'Steak,Onion,Ginger,Peanuts,Fire Spice,Soy Sauce,Sake,Cornstarch,Sugar', 'Gong Bao Beef,Gong Bao Beef,Gong Bao Beef');
INSERT INTO `monster_recipes` VALUES (241, 'Steak,Onion,Ginger,Peanuts,Fire Spice,Soy Sauce,Sake,Cornstarch,Brown Sugar', 'Gong Bao Beef,Gong Bao Beef,Gong Bao Beef');
INSERT INTO `monster_recipes` VALUES (242, 'Peanuts,Peanuts', 'Peanut Butter');
INSERT INTO `monster_recipes` VALUES (243, 'Peanut Butter,White Bread,Red Jelly', 'PB&J Triangles,PB&J Triangles');
INSERT INTO `monster_recipes` VALUES (244, 'Peanut Butter,Wheat Bread,Red Jelly', 'PB&J Triangles,PB&J Triangles');
INSERT INTO `monster_recipes` VALUES (245, 'Peanut Butter,White Bread,Purple Jelly', 'PB&J Triangles,PB&J Triangles');
INSERT INTO `monster_recipes` VALUES (246, 'Peanut Butter,Wheat Bread,Purple Jelly', 'PB&J Triangles,PB&J Triangles');
INSERT INTO `monster_recipes` VALUES (247, 'Peanut Butter,White Bread,Swirled Jelly', 'PB&J Triangles,PB&J Triangles');
INSERT INTO `monster_recipes` VALUES (248, 'Peanut Butter,White Bread,Swirled Jelly', 'PB&J Triangles,PB&J Triangles');
INSERT INTO `monster_recipes` VALUES (249, 'Fish,Orange,Ginger', 'Orange-Ginger Fish,Orange-Ginger Fish');
INSERT INTO `monster_recipes` VALUES (250, 'Chicken,Redsberry Wine,Onion', 'Coq au Vin,Coq au Vin,Coq au Vin');
INSERT INTO `monster_recipes` VALUES (264, 'Cream,Sugar,Egg,Butter,Baking Chocolate', 'Chocolate Soufflé,Chocolate Soufflé,Chocolate Soufflé');
INSERT INTO `monster_recipes` VALUES (252, 'Cream,Onion,Flour,Potato', 'Cream of Potato Soup,Cream of Potato Soup,Cream of Potato Soup,Cream of Potato Soup');
INSERT INTO `monster_recipes` VALUES (253, 'Milk,Onion,Flour,Potato', 'Cream of Potato Soup,Cream of Potato Soup,Cream of Potato Soup,Cream of Potato Soup');
INSERT INTO `monster_recipes` VALUES (254, '4-Leaf Clover,Tea Leaves', 'Fortune''s Tea');
INSERT INTO `monster_recipes` VALUES (256, 'Ginger,Sour Lime,Sugar,Yeast,Aging Root', 'Ginger Beer,Ginger Beer,Ginger Beer,Ginger Beer,Ginger Beer,Ginger Beer');
INSERT INTO `monster_recipes` VALUES (257, 'Sugar,Shortening,Egg,Flour', 'Sugar Cookies,Sugar Cookies,Sugar Cookies,Sugar Cookies,Sugar Cookies');
INSERT INTO `monster_recipes` VALUES (258, 'Sugar,Shortening,Egg,Flour,Chocolate Drops', 'Chocolate Chip Cookies,Chocolate Chip Cookies,Chocolate Chip Cookies,Chocolate Chip Cookies,Chocolate Chip Cookies');
INSERT INTO `monster_recipes` VALUES (259, 'Sugar,Shortening,Speckled Egg,Flour', 'Sugar Cookies,Sugar Cookies,Sugar Cookies,Sugar Cookies,Sugar Cookies');
INSERT INTO `monster_recipes` VALUES (260, 'Sugar,Shortening,Speckled Egg,Flour,Chocolate Drops', 'Chocolate Chip Cookies,Chocolate Chip Cookies,Chocolate Chip Cookies,Chocolate Chip Cookies,Chocolate Chip Cookies');
INSERT INTO `monster_recipes` VALUES (261, 'Appleberry Seeds,Aging Root', 'Appleberry Bush');
INSERT INTO `monster_recipes` VALUES (263, 'Wheat Bread,Peanuts,Chicken,Egg,Butter', 'Peanut-Crusted Chicken Breast,Peanut-Crusted Chicken Breast,Peanut-Crusted Chicken Breast');
INSERT INTO `monster_recipes` VALUES (265, 'Cream,Sugar,Speckled Egg,Butter,Baking Chocolate', 'Chocolate Soufflé,Chocolate Soufflé,Chocolate Soufflé');
INSERT INTO `monster_recipes` VALUES (266, 'Wild Oats,Sugar', 'Plain Granola');
INSERT INTO `monster_recipes` VALUES (267, 'Wild Oats,Sugar,Blueberries', 'Raisin Granola');
INSERT INTO `monster_recipes` VALUES (268, 'Wild Oats,Sugar,Redsberries', 'Raisin Granola');
INSERT INTO `monster_recipes` VALUES (269, 'Wheat', 'Flour');
INSERT INTO `monster_recipes` VALUES (270, 'Empty Fishbowl,Fish', 'Fishbowl');
INSERT INTO `monster_recipes` VALUES (271, 'Empty Fishbowl,Steak', 'Fishbowl with Steak');
INSERT INTO `monster_recipes` VALUES (272, 'Empty Fishbowl,Chicken', 'Fishbowl with Chicken');
INSERT INTO `monster_recipes` VALUES (273, 'Clover Leaf,Clover Leaf,Clover Leaf', '3-Leaf Clover');
INSERT INTO `monster_recipes` VALUES (274, '3-Leaf Clover,Clover Leaf', '4-Leaf Clover');
INSERT INTO `monster_recipes` VALUES (275, '4-Leaf Clover,Clover Leaf', '5-Leaf Clover');
INSERT INTO `monster_recipes` VALUES (276, 'Clover Leaf,Clover Leaf,Clover Leaf,Clover Leaf', '4-Leaf Clover');
INSERT INTO `monster_recipes` VALUES (277, 'Clover Leaf,Clover Leaf,Clover Leaf,Clover Leaf,Clover Leaf', '5-Leaf Clover');
INSERT INTO `monster_recipes` VALUES (278, 'Leafy Cabbage,Aging Root', 'Sauerkraut,Sauerkraut,Sauerkraut');
INSERT INTO `monster_recipes` VALUES (279, 'Steak,White Bread', 'Hamburger,Hamburger,Hamburger');
INSERT INTO `monster_recipes` VALUES (280, 'Steak,Wheat Bread', 'Hamburger,Hamburger,Hamburger');
INSERT INTO `monster_recipes` VALUES (281, 'Steak,White Bread,Cheese', 'Cheese Hamburger,Cheese Hamburger,Cheese Hamburger');
INSERT INTO `monster_recipes` VALUES (282, 'Steak,Wheat Bread,Cheese', 'Cheese Hamburger,Cheese Hamburger,Cheese Hamburger');
INSERT INTO `monster_recipes` VALUES (283, 'Steak,White Bread,Onion,Leafy Cabbage,Tomato', 'Dressed Hamburger,Dressed Hamburger,Dressed Hamburger');
INSERT INTO `monster_recipes` VALUES (284, 'Steak,Wheat Bread,Onion,Leafy Cabbage,Tomato', 'Dressed Hamburger,Dressed Hamburger,Dressed Hamburger');
INSERT INTO `monster_recipes` VALUES (285, 'Steak,White Bread,Cheese,Onion,Leafy Cabbage,Tomato', 'Dressed Cheese Hamburger,Dressed Cheese Hamburger,Dressed Cheese Hamburger');
INSERT INTO `monster_recipes` VALUES (286, 'Steak,Wheat Bread,Cheese,Onion,Leafy Cabbage,Tomato', 'Dressed Cheese Hamburger,Dressed Cheese Hamburger,Dressed Cheese Hamburger');
INSERT INTO `monster_recipes` VALUES (287, 'Steak,White Bread,Cheese,Onion,Leafy Cabbage,Tomato,Egg,Beet', 'Australian Hamburger,Australian Hamburger,Australian Hamburger');
INSERT INTO `monster_recipes` VALUES (288, 'Steak,Wheat Bread,Cheese,Onion,Leafy Cabbage,Tomato,Egg,Beet', 'Australian Hamburger,Australian Hamburger,Australian Hamburger');
INSERT INTO `monster_recipes` VALUES (289, 'Steak,White Bread,Cheese,Onion,Leafy Cabbage,Tomato,Speckled Egg,Beet', 'Australian Hamburger,Australian Hamburger,Australian Hamburger');
INSERT INTO `monster_recipes` VALUES (290, 'Steak,Wheat Bread,Cheese,Onion,Leafy Cabbage,Tomato,Speckled Egg,Beet', 'Australian Hamburger,Australian Hamburger,Australian Hamburger');
INSERT INTO `monster_recipes` VALUES (291, 'Corn Syrup,Flour,Sugar,Cornstarch,Redsberries', 'Redsberry Twists,Redsberry Twists,Redsberry Twists,Redsberry Twists,Redsberry Twists');
INSERT INTO `monster_recipes` VALUES (292, 'Corn Syrup,Flour,Sugar,Cornstarch,Blueberries', 'Wild Blueberry Twists,Wild Blueberry Twists,W,Wild Blueberry Twists,Wild Blueberry Twistsild Blueberry Twists');
INSERT INTO `monster_recipes` VALUES (293, 'Corn Syrup,Flour,Sugar,Cornstarch,Baking Chocolate', 'Chocolate Twists,Chocolate Twists,Chocolate Twists,Chocolate Twists,Chocolate Twists');
INSERT INTO `monster_recipes` VALUES (294, 'Coconut,Aging Root,Sugar', 'Coconut Cordial');
INSERT INTO `monster_recipes` VALUES (295, 'Greenish Leaf,Aging Root', 'Autumn Leaf');
INSERT INTO `monster_recipes` VALUES (296, 'Flour,Shortening', 'Pie Crust');
INSERT INTO `monster_recipes` VALUES (297, 'Flour,Butter', 'Pie Crust');
INSERT INTO `monster_recipes` VALUES (305, 'Egg,Sweet Tea,Soy Sauce', 'Tea Egg');
INSERT INTO `monster_recipes` VALUES (306, 'Speckled Egg,Tea Leaves,Sugar,Soy Sauce', 'Tea Egg');
INSERT INTO `monster_recipes` VALUES (307, 'Speckled Egg,Sweet Tea,Soy Sauce', 'Tea Egg');
INSERT INTO `monster_recipes` VALUES (308, 'Tea Leaves,Holly', 'Yerba Mate');
INSERT INTO `monster_recipes` VALUES (310, 'Baking Chocolate,Sugar,Mint Leaves', 'Minty Chocolate Bar,Minty Chocolate Bar');
