It is clear that early translators of the Book of Ki Ri chose not to translate some words, especially in the names of the gods.  Perhaps they felt there was not a suitable translation, or perhaps they saw the words which made up these names as the names themselves, and chose, therefore, not to translate them anymore than you would translate "Bob" from English to French.  Whatever the reason, some of these decisions have lead to confusion for today's readers.  Hoping to clear the confusion, several archeologists, linguists, and historians, including myself, have searched through countless ruins and mulled over numerous Ancient texts hoping to gain a clearer perspective on early translation of the Book of Ki Ri, especially concerning the names of people, places, as the gods themselves.<br />
<br />
The Ancient language did not have a distinction between capital and lowercase letters, but there was a modification of the symbols which would identify a word as a proper noun.  For example, many people of the time carried names that were the word for "mountain" or other features of landscape.  There is a clear "accent mark," if you will, on these words when they are referring to a person's name.  Ki Ri Kashu, for example, is actually three words of the Ancient language, two of which being highly common.<br />
<br />
The word "kashu" means, for all intents and purposes, "god."  In the case of Ki Ri Kashu, we have, literally, "One All God."  This can generally be understood to mean "The All God," or "God of The All."  Though the Ancient language did not have the word "the", the use of "one" in this case bears the same meaning.<br />
<br />
Kaera Ki Ri Kashu is, of course, Ki Ri Kashu's Daughter, or literally, "Daughter (of) Ki Ri Kashu."  The word "of" is implied.  And, according to legend, Rigzi Vizgi is the daughter's Gemini, or twin.  The exact meaning is difficult to translate, but "rigzi vizgi" roughly means "the same, but opposite."  If this civilization had discovered Newton's Third Law of Motion, they probably would have called it "rigzi vizgi" as well.<br />
<br />
Rigzi Vizgi's full name should probably have been translated as Rigzi Vizgi Kaera Ki Ri Kashu, or perhaps Kaera Ki Ri Kashu Rigzi Vizgi.  We can see why early translators would have chosen to shorten the name to simply Rigzi Vizgi.<br />
<br />
The word "gijubi" is relatively simple: it means "earth."  There is the connotation that this is earth which grows things.  How people decided what kind of earth grows things is difficult.  From context it seems that gijubi can be tilled or untilled, watered or dried, and it doesn't even have to have signs of growth on it at the time.  It appears that so long as the particular ground which you are observing could be believed to support life, it could be called "gijubi."  This specificness suggests that the God's name could have come before the common word.  Though it would be highly irregular, given almost every other name referred to in Ancient text, if an exception were to be made for anything, it might as well be for a god.<br />