<?php
if($okay_to_be_here !== true)
  exit();
?>
<style type="text/css">
blockquote
{
  padding-left: 4em;
  padding-right: 2em;
  padding-bottom: 1em;
  display: block;
}

h5 { text-align: center; }

.booktext *
{
  line-height: 200%;
}
</style>
<div class="booktext">
<h5>Chapter 6. Baskerville Hall</h5>
<p>Sir Henry Baskerville and Dr. Mortimer were ready upon the appointed day, and we started as arranged for Devonshire. Mr. Sherlock Holmes drove with me to the station and gave me his last parting injunctions and advice.</p>
<p>"I will not bias your mind by suggesting theories or suspicions, Watson," said he; "I wish you simply to report facts in the fullest possible manner to me, and you can leave me to do the theorizing."</p>
<p>"What sort of facts?" I asked.</p>
<p>"Anything which may seem to have a bearing however indirect upon the case, and especially the relations between young Baskerville and his neighbours or any fresh particulars concerning the death of Sir Charles. I have made some inquiries myself in the last few days, but the results have, I fear, been negative. One thing only appears to be certain, and that is that Mr. James Desmond, who is the next heir, is an elderly gentleman of a very amiable disposition, so that this persecution does not arise from him. I really think that we may eliminate him entirely from our calculations. There remain the people who will actually surround Sir Henry Baskerville upon the moor."</p>
<p>"Would it not be well in the first place to get rid of this Barrymore couple?"</p>
<p>"By no means. You could not make a greater mistake. If they are innocent it would be a cruel injustice, and if they are guilty we should be giving up all chance of bringing it home to them. No, no, we will preserve them upon our list of suspects. Then there is a groom at the Hall, if I remember right. There are two moorland farmers. There is our friend Dr. Mortimer, whom I believe to be entirely honest, and there is his wife, of whom we know nothing. There is this naturalist, Stapleton, and there is his sister, who is said to be a young lady of attractions. There is Mr. Frankland, of Lafter Hall, who is also an unknown factor, and there are one or two other neighbours. These are the folk who must be your very special study."</p>
<p>"I will do my best."</p>
<p>"You have arms, I suppose?"</p>
<p>"Yes, I thought it as well to take them."</p>
<p>"Most certainly. Keep your revolver near you night and day, and never relax your precautions."</p>
<p>Our friends had already secured a first-class carriage and were waiting for us upon the platform.</p>
<p>"No, we have no news of any kind," said Dr. Mortimer in answer to my friend's questions. "I can swear to one thing, and that is that we have not been shadowed during the last two days. We have never gone out without keeping a sharp watch, and no one could have escaped our notice."</p>
<p>"You have always kept together, I presume?"</p>
<p>"Except yesterday afternoon. I usually give up one day to pure amusement when I come to town, so I spent it at the Museum of the College of Surgeons."</p>
<p>"And I went to look at the folk in the park," said Baskerville.</p>
<p>"But we had no trouble of any kind."</p>
<p>"It was imprudent, all the same," said Holmes, shaking his head and looking very grave. "I beg, Sir Henry, that you will not go about alone. Some great misfortune will befall you if you do. Did you get your other boot?"</p>
<p>"No, sir, it is gone forever."</p>
<p>"Indeed. That is very interesting. Well, good-bye," he added as the train began to glide down the platform. "Bear in mind, Sir Henry, one of the phrases in that queer old legend which Dr. Mortimer has read to us, and avoid the moor in those hours of darkness when the powers of evil are exalted."</p>
<p>I looked back at the platform when we had left it far behind and saw the tall, austere figure of Holmes standing motionless and gazing after us.</p>
<p>The journey was a swift and pleasant one, and I spent it in making the more intimate acquaintance of my two companions and in playing with Dr. Mortimer's spaniel. In a very few hours the brown earth had become ruddy, the brick had changed to granite, and red cows grazed in well-hedged fields where the lush grasses and more luxuriant vegetation spoke of a richer, if a damper, climate. Young Baskerville stared eagerly out of the window and cried aloud with delight as he recognized the familiar features of the Devon scenery.</p>
<p>"I've been over a good part of the world since I left it, Dr. Watson," said he; "but I have never seen a place to compare with it."</p>
<p>"I never saw a Devonshire man who did not swear by his county," I remarked.</p>
<p>"It depends upon the breed of men quite as much as on the county," said Dr. Mortimer. "A glance at our friend here reveals the rounded head of the Celt, which carries inside it the Celtic enthusiasm and power of attachment. Poor Sir Charles's head was of a very rare type, half Gaelic, half Ivernian in its characteristics. But you were very young when you last saw Baskerville Hall, were you not?"</p>
<p>"I was a boy in my teens at the time of my father's death and had never seen the Hall, for he lived in a little cottage on the South Coast. Thence I went straight to a friend in America. I tell you it is all as new to me as it is to Dr. Watson, and I'm as keen as possible to see the moor."</p>
<p>"Are you? Then your wish is easily granted, for there is your first sight of the moor," said Dr. Mortimer, pointing out of the carriage window.</p>
<p>Over the green squares of the fields and the low curve of a wood there rose in the distance a gray, melancholy hill, with a strange jagged summit, dim and vague in the distance, like some fantastic landscape in a dream. Baskerville sat for a long time, his eyes fixed upon it, and I read upon his eager face how much it meant to him, this first sight of that strange spot where the men of his blood had held sway so long and left their mark so deep. There he sat, with his tweed suit and his American accent, in the corner of a prosaic railway-carriage, and yet as I looked at his dark and expressive face I felt more than ever how true a descendant he was of that long line of high-blooded, fiery, and masterful men. There were pride, valour, and strength in his thick brows, his sensitive nostrils, and his large hazel eyes. If on that forbidding moor a difficult and dangerous quest should lie before us, this was at least a comrade for whom one might venture to take a risk with the certainty that he would bravely share it.</p>
<p>The train pulled up at a small wayside station and we all descended. Outside, beyond the low, white fence, a wagonette with a pair of cobs was waiting. Our coming was evidently a great event, for station-master and porters clustered round us to carry out our luggage. It was a sweet, simple country spot, but I was surprised to observe that by the gate there stood two soldierly men in dark uniforms who leaned upon their short rifles and glanced keenly at us as we passed. The coachman, a hard-faced, gnarled little fellow, saluted Sir Henry Baskerville, and in a few minutes we were flying swiftly down the broad, white road. Rolling pasture lands curved upward on either side of us, and old gabled houses peeped out from amid the thick green foliage, but behind the peaceful and sunlit countryside there rose ever, dark against the evening sky, the long, gloomy curve of the moor, broken by the jagged and sinister hills.</p>
<p>The wagonette swung round into a side road, and we curved upward through deep lanes worn by centuries of wheels, high banks on either side, heavy with dripping moss and fleshy hart's-tongue ferns. Bronzing bracken and mottled bramble gleamed in the light of the sinking sun. Still steadily rising, we passed over a narrow granite bridge and skirted a noisy stream which gushed swiftly down, foaming and roaring amid the gray boulders. Both road and stream wound up through a valley dense with scrub oak and fir. At every turn Baskerville gave an exclamation of delight, looking eagerly about him and asking countless questions. To his eyes all seemed beautiful, but to me a tinge of melancholy lay upon the countryside, which bore so clearly the mark of the waning year. Yellow leaves carpeted the lanes and fluttered down upon us as we passed. The rattle of our wheels died away as we drove through drifts of rotting vegetation—sad gifts, as it seemed to me, for Nature to throw before the carriage of the returning heir of the Baskervilles.</p>
<p>"Halloa!" cried Dr. Mortimer, "what is this?"</p>
<p>A steep curve of heath-clad land, an outlying spur of the moor, lay in front of us. On the summit, hard and clear like an equestrian statue upon its pedestal, was a mounted soldier, dark and stern, his rifle poised ready over his forearm. He was watching the road along which we travelled.</p>
<p>"What is this, Perkins?" asked Dr. Mortimer.</p>
<p>Our driver half turned in his seat. "There's a convict escaped from Princetown, sir. He's been out three days now, and the warders watch every road and every station, but they've had no sight of him yet. The farmers about here don't like it, sir, and that's a fact."</p>
<p>"Well, I understand that they get five pounds if they can give information."</p>
<p>"Yes, sir, but the chance of five pounds is but a poor thing compared to the chance of having your throat cut. You see, it isn't like any ordinary convict. This is a man that would stick at nothing."</p>
<p>"Who is he, then?"</p>
<p>"It is Selden, the Notting Hill murderer."</p>
<p>I remembered the case well, for it was one in which Holmes had taken an interest on account of the peculiar ferocity of the crime and the wanton brutality which had marked all the actions of the assassin. The commutation of his death sentence had been due to some doubts as to his complete sanity, so atrocious was his conduct. Our wagonette had topped a rise and in front of us rose the huge expanse of the moor, mottled with gnarled and craggy cairns and tors. A cold wind swept down from it and set us shivering. Somewhere there, on that desolate plain, was lurking this fiendish man, hiding in a burrow like a wild beast, his heart full of malignancy against the whole race which had cast him out. It needed but this to complete the grim suggestiveness of the barren waste, the chilling wind, and the darkling sky. Even Baskerville fell silent and pulled his overcoat more closely around him.</p>
<p>We had left the fertile country behind and beneath us. We looked back on it now, the slanting rays of a low sun turning the streams to threads of gold and glowing on the red earth new turned by the plough and the broad tangle of the woodlands. The road in front of us grew bleaker and wilder over huge russet and olive slopes, sprinkled with giant boulders. Now and then we passed a moorland cottage, walled and roofed with stone, with no creeper to break its harsh outline. Suddenly we looked down into a cuplike depression, patched with stunted oaks and firs which had been twisted and bent by the fury of years of storm. Two high, narrow towers rose over the trees. The driver pointed with his whip.</p>
<p>"Baskerville Hall," said he.</p>
<p>Its master had risen and was staring with flushed cheeks and shining eyes. A few minutes later we had reached the lodge-gates, a maze of fantastic tracery in wrought iron, with weather-bitten pillars on either side, blotched with lichens, and surmounted by the boars' heads of the Baskervilles. The lodge was a ruin of black granite and bared ribs of rafters, but facing it was a new building, half constructed, the first fruit of Sir Charles's South African gold.</p>
<p>Through the gateway we passed into the avenue, where the wheels were again hushed amid the leaves, and the old trees shot their branches in a sombre tunnel over our heads. Baskerville shuddered as he looked up the long, dark drive to where the house glimmered like a ghost at the farther end.</p>
<p>"Was it here?" he asked in a low voice.</p>
<p>"No, no, the yew alley is on the other side."</p>
<p>The young heir glanced round with a gloomy face.</p>
<p>"It's no wonder my uncle felt as if trouble were coming on him in such a place as this," said he. "It's enough to scare any man. I'll have a row of electric lamps up here inside of six months, and you won't know it again, with a thousand candle-power Swan and Edison right here in front of the hall door."</p>
<p>The avenue opened into a broad expanse of turf, and the house lay before us. In the fading light I could see that the centre was a heavy block of building from which a porch projected. The whole front was draped in ivy, with a patch clipped bare here and there where a window or a coat of arms broke through the dark veil. From this central block rose the twin towers, ancient, crenelated, and pierced with many loopholes. To right and left of the turrets were more modern wings of black granite. A dull light shone through heavy mullioned windows, and from the high chimneys which rose from the steep, high-angled roof there sprang a single black column of smoke.</p>
<p>"Welcome, Sir Henry! Welcome to Baskerville Hall!"</p>
<p>A tall man had stepped from the shadow of the porch to open the door of the wagonette. The figure of a woman was silhouetted against the yellow light of the hall. She came out and helped the man to hand down our bags.</p>
<p>"You don't mind my driving straight home, Sir Henry?" said Dr. Mortimer. "My wife is expecting me."</p>
<p>"Surely you will stay and have some dinner?"</p>
<p>"No, I must go. I shall probably find some work awaiting me. I would stay to show you over the house, but Barrymore will be a better guide than I. Good-bye, and never hesitate night or day to send for me if I can be of service."</p>
<p>The wheels died away down the drive while Sir Henry and I turned into the hall, and the door clanged heavily behind us. It was a fine apartment in which we found ourselves, large, lofty, and heavily raftered with huge baulks of age-blackened oak. In the great old-fashioned fireplace behind the high iron dogs a log-fire crackled and snapped. Sir Henry and I held out our hands to it, for we were numb from our long drive. Then we gazed round us at the high, thin window of old stained glass, the oak panelling, the stags' heads, the coats of arms upon the walls, all dim and sombre in the subdued light of the central lamp.</p>
<p>"It's just as I imagined it," said Sir Henry. "Is it not the very picture of an old family home? To think that this should be the same hall in which for five hundred years my people have lived. It strikes me solemn to think of it."</p>
<p>I saw his dark face lit up with a boyish enthusiasm as he gazed about him. The light beat upon him where he stood, but long shadows trailed down the walls and hung like a black canopy above him. Barrymore had returned from taking our luggage to our rooms. He stood in front of us now with the subdued manner of a well-trained servant. He was a remarkable-looking man, tall, handsome, with a square black beard and pale, distinguished features.</p>
<p>"Would you wish dinner to be served at once, sir?"</p>
<p>"Is it ready?"</p>
<p>"In a very few minutes, sir. You will find hot water in your rooms. My wife and I will be happy, Sir Henry, to stay with you until you have made your fresh arrangements, but you will understand that under the new conditions this house will require a considerable staff."</p>
<p>"What new conditions?"</p>
<p>"I only meant, sir, that Sir Charles led a very retired life, and we were able to look after his wants. You would, naturally, wish to have more company, and so you will need changes in your household."</p>
<p>"Do you mean that your wife and you wish to leave?"</p>
<p>"Only when it is quite convenient to you, sir."</p>
<p>"But your family have been with us for several generations, have they not? I should be sorry to begin my life here by breaking an old family connection."</p>
<p>I seemed to discern some signs of emotion upon the butler's white face.</p>
<p>"I feel that also, sir, and so does my wife. But to tell the truth, sir, we were both very much attached to Sir Charles, and his death gave us a shock and made these surroundings very painful to us. I fear that we shall never again be easy in our minds at Baskerville Hall."</p>
<p>"But what do you intend to do?"</p>
<p>"I have no doubt, sir, that we shall succeed in establishing ourselves in some business. Sir Charles's generosity has given us the means to do so. And now, sir, perhaps I had best show you to your rooms."</p>
<p>A square balustraded gallery ran round the top of the old hall, approached by a double stair. From this central point two long corridors extended the whole length of the building, from which all the bedrooms opened. My own was in the same wing as Baskerville's and almost next door to it. These rooms appeared to be much more modern than the central part of the house, and the bright paper and numerous candles did something to remove the sombre impression which our arrival had left upon my mind.</p>
<p>But the dining-room which opened out of the hall was a place of shadow and gloom. It was a long chamber with a step separating the dais where the family sat from the lower portion reserved for their dependents. At one end a minstrel's gallery overlooked it. Black beams shot across above our heads, with a smoke-darkened ceiling beyond them. With rows of flaring torches to light it up, and the colour and rude hilarity of an old-time banquet, it might have softened; but now, when two black-clothed gentlemen sat in the little circle of light thrown by a shaded lamp, one's voice became hushed and one's spirit subdued. A dim line of ancestors, in every variety of dress, from the Elizabethan knight to the buck of the Regency, stared down upon us and daunted us by their silent company. We talked little, and I for one was glad when the meal was over and we were able to retire into the modern billiard-room and smoke a cigarette.</p>
<p>"My word, it isn't a very cheerful place," said Sir Henry. "I suppose one can tone down to it, but I feel a bit out of the picture at present. I don't wonder that my uncle got a little jumpy if he lived all alone in such a house as this. However, if it suits you, we will retire early tonight, and perhaps things may seem more cheerful in the morning."</p>
<p>I drew aside my curtains before I went to bed and looked out from my window. It opened upon the grassy space which lay in front of the hall door. Beyond, two copses of trees moaned and swung in a rising wind. A half moon broke through the rifts of racing clouds. In its cold light I saw beyond the trees a broken fringe of rocks, and the long, low curve of the melancholy moor. I closed the curtain, feeling that my last impression was in keeping with the rest.</p>
<p>And yet it was not quite the last. I found myself weary and yet wakeful, tossing restlessly from side to side, seeking for the sleep which would not come. Far away a chiming clock struck out the quarters of the hours, but otherwise a deathly silence lay upon the old house. And then suddenly, in the very dead of the night, there came a sound to my ears, clear, resonant, and unmistakable. It was the sob of a woman, the muffled, strangling gasp of one who is torn by an uncontrollable sorrow. I sat up in bed and listened intently. The noise could not have been far away and was certainly in the house. For half an hour I waited with every nerve on the alert, but there came no other sound save the chiming clock and the rustle of the ivy on the wall.</p>
</div>
