<?php
$_GET['maintenance'] = 'no';

require_once $_SERVER['DOCUMENT_ROOT'] . '/commons/init.php';

$require_petload = 'no';

// confirm the session...
require_once 'commons/dbconnect.php';
require_once 'commons/rpgfunctions.php';
require_once 'commons/sessions.php';
require_once 'commons/grammar.php';
require_once 'commons/formatting.php';

if($admin['manageitems'] != 'yes')
{
  header('Location: /admin/tools.php');
  exit();
}

if(array_key_exists('give', $_GET))
{
  $id = (int)$_GET['give'];
  $command = 'SELECT ingredients FROM monster_recipes WHERE idnum=' . $id . ' LIMIT 1';
  $recipe = $database->FetchSingle($command, 'fetching recipe for debugging');

  $items = explode(',', $recipe['ingredients']);
  foreach($items as $item)
    add_inventory_cached($user['user'], 'u:' . $user['idnum'], $item, 'Generated by the Recipe Editor for debugging purposes', 'storage/incoming');

  process_cached_inventory();

  flag_new_incoming_items($user['user']);

  header('Location: ./incoming.php?msg=13:incoming');
  exit();
}

include 'commons/html.php';
?>
 <head>
  <title><?= $SETTINGS['site_name'] ?> &gt; Administrative Tools &gt; Recipe Editor</title>
<?php include "commons/head.php"; ?>
 </head>
 <body>
<?php include 'commons/header_2.php'; ?>
     <h4><a href="/admin/tools.php">Administrative Tools</a> &gt; Recipe Editor</h4>
<table>
<tr class="titlerow">
 <th></th>
 <th class="centered">#</th>
 <th>Ingredients</th>
 <th>Makes</th>
</tr>
<?php
$command = 'SELECT * FROM monster_recipes ORDER BY idnum ASC';
$result = mysql_query($command);

$bgcolor = begin_row_class();

while($recipe = mysql_fetch_assoc($result))
{
  $ingredients = explode(',', $recipe['ingredients']);
  $makes = explode(',', $recipe['makes']);

  $bad_ingredients = array();
  $bad_makes = array();

  $test_ingredients = array_unique($ingredients);
  
  foreach($test_ingredients as $item)
  {
    $details = get_item_byname($item);
    if($details == false)
      $bad_ingredients[] = $item;
  }

  $test_makes = array_unique($makes);

  foreach($test_makes as $item)
  {
    $details = get_item_byname($item);
    if($details == false)
      $bad_makes[] = $item;
  }
?>
<tr class="<?= $bgcolor ?>">
 <td><a href="adminrecipeeditor.php?give=<?= $recipe['idnum'] ?>">&gt;</a></td>
 <td class="centered"><?= $recipe['idnum'] ?></td>
 <td><?php
  echo str_replace(',', ', ', $recipe['ingredients']);
  
  if(count($bad_ingredients) > 0)
    echo '<br /><span class="failure">' . implode(', ', $bad_ingredients) . ' are not items!</span>';
?></td>
 <td><?php
  echo str_replace(',', ', ', $recipe['makes']);

  if(count($bad_makes) > 0)
    echo '<br /><span class="failure">' . implode(', ', $bad_makes) . ' are not items!</span>';
?></td>
</tr>
<?php
  $bgcolor = alt_row_class($bgcolor);
}
?>
</table>
<?php include 'commons/footer_2.php'; ?>
 </body>
</html>
